/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelIndicator.java
 *
 * Created on May 6, 2011, 12:29:40 PM
 */
package co.edu.udea.ludens.applet.gui;

import javax.swing.JLabel;

/**
 *
 * @author juanga
 */
public class PanelIndicator extends javax.swing.JPanel {

    /**
     * Creates new form PanelIndicator
     */
    public PanelIndicator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbIcon = new javax.swing.JLabel();
        lbNameElement = new javax.swing.JLabel();
        lbNameContent = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(297, 40));
        setLayout(new java.awt.GridLayout());

        lbIcon.setPreferredSize(new java.awt.Dimension(40, 40));
        add(lbIcon);

        lbNameElement.setText("jLabel1");
        add(lbNameElement);

        lbNameContent.setText("jLabel2");
        add(lbNameContent);
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLbIcon() {

        return (this.lbIcon);
    }

    public JLabel getLbNameElement() {

        return (this.lbNameElement);
    }

    public JLabel getLbNameContent() {

        return (this.lbNameContent);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbIcon;
    private javax.swing.JLabel lbNameContent;
    private javax.swing.JLabel lbNameElement;
    // End of variables declaration//GEN-END:variables
}
